name: api

on:
  push:
    branches:
      - main
    paths:
      - api/**
  pull_request:
    branches:
      - main
    paths:
      - api/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: "16"
          distribution: "adopt"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: api
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: api
